import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/organism/Header";
import Footer from "@/components/organism/Footer";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-gradient-to-b from-slate-50 to-slate-100">
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
